import type { Metadata } from 'next';
import { Single_Day } from 'next/font/google';
import './globals.css';

const singleDay = Single_Day({
  variable: '--font-single-day',
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang="ko">
    <body className={`${singleDay.variable} antialiased`} style={{ fontFamily: 'var(--font-single-day)' }}>
      <div className="text-14 text-secondary">안녕하세요!</div>
      {children}
    </body>
  </html>
);

export default RootLayout;
